config/routes.rb
Hocpoc::Application.routes.draw do
  resources :dashboards
  root :to => 'dashboards#index'

  match 'hometemps' => 'home_temps#index'
  match 'hometemps/data' => 'home_temps#data'
  match 'hometemps/temp' => 'home_temps#temp'
  match 'hometemps/humidity' => 'home_temps#humidity'

end

app/models/dashboard.rb
class Dashboard < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/home_temp.rb
class HomeTemp < ActiveRecord::Base
  attr_accessible :humidity, :temp, :hvac_heater_state, :hvac_fan_state

  def self.retrieve_data
    logger.info "#{Time.now} - HomeTemp.retrieve_data - Start"

    @nest = NestThermostat::Nest.new({email: ENV['NEST_EMAIL'], password: ENV['NEST_PASS']})

    if @nest
      logger.info "#{Time.now} - HomeTemp.retrieve_data - Write to DB"
      HomeTemp.create(
        :temp => @nest.current_temp,
        :humidity => @nest.humidity,
        :hvac_heater_state => @nest.status["shared"][@nest.device_id]["hvac_heater_state"],
        :hvac_fan_state => @nest.status["shared"][@nest.device_id]["hvac_fan_state"]
      )
    else
      logger.error "#{Time.now} - HomeTemp.retrieve_data - Error establishing connection"
    end

    logger.info "#{Time.now} - HomeTemp.retrieve_data - End"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  # GET /dashboards
  # GET /dashboards.json
  def index
    @hometemps = HomeTemp.select("created_at, temp")

    @hometemps.map! {|h| {:x => h.created_at.to_i, :y => h.temp.to_f}}

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @hometemps }
    end
  end

  # GET /dashboards/1
  # GET /dashboards/1.json
  def show
    @dashboard = Dashboard.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dashboard }
    end
  end

  # GET /dashboards/new
  # GET /dashboards/new.json
  def new
    @dashboard = Dashboard.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dashboard }
    end
  end

  # GET /dashboards/1/edit
  def edit
    @dashboard = Dashboard.find(params[:id])
  end

  # POST /dashboards
  # POST /dashboards.json
  def create
    @dashboard = Dashboard.new(params[:dashboard])

    respond_to do |format|
      if @dashboard.save
        format.html { redirect_to @dashboard, notice: 'Dashboard was successfully created.' }
        format.json { render json: @dashboard, status: :created, location: @dashboard }
      else
        format.html { render action: "new" }
        format.json { render json: @dashboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /dashboards/1
  # PUT /dashboards/1.json
  def update
    @dashboard = Dashboard.find(params[:id])

    respond_to do |format|
      if @dashboard.update_attributes(params[:dashboard])
        format.html { redirect_to @dashboard, notice: 'Dashboard was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dashboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dashboards/1
  # DELETE /dashboards/1.json
  def destroy
    @dashboard = Dashboard.find(params[:id])
    @dashboard.destroy

    respond_to do |format|
      format.html { redirect_to dashboards_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_temps_controller.rb
class HomeTempsController < ApplicationController
  # GET /hometemps/data
  def data
    @temp = HomeTemp.select("created_at, temp, humidity")
    @temp.map! {|h| {:x => h.created_at.to_i, :y => h.temp.to_f}}
    @data = []
    @data << {:name => "Temp", :data => @temp}

    @humidity = HomeTemp.select("created_at, humidity")
    @humidity.map! {|h| {:x => h.created_at.to_i, :y => h.humidity.to_f}}
    @data << {:name => "Humidity", :data => @humidity}

    @hvac_heat = HomeTemp.select {"created_at, hvac_heater_state"}
    @hvac_heat.map! {|h|
      h.hvac_heater_state ? heater_val = 20 : heater_val = 0
      {:x => h.created_at.to_i, :y => heater_val}
    }
    @data << {:name => "Heater", :data => @hvac_heat}

    render json: @data
  end
  # GET /hometemps/temp
  def temp
    @temp = HomeTemp.select("created_at, temp")
    @temp.map! {|h| {:x => h.created_at.to_i, :y => h.temp.to_f}}
    @data = []
    @data << {:name => "Temp", :data => @temp}
    render json: @data
  end

  # GET /hometemps/humidity
  def humidity
    @humidity = HomeTemp.select("created_at, humidity")
    @humidity.map! {|h| {:x => h.created_at.to_i, :y => h.humidity.to_f}}
    @data = []
    @data << {:name => "Humidity", :data => @humidity}
    render json: @data
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/home_temps_helper.rb
module HomeTempsHelper
end

app/views/dashboards/_form.html.erb
<%= form_for(@dashboard) do |f| %>
  <% if @dashboard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dashboard.errors.count, "error") %> prohibited this dashboard from being saved:</h2>

      <ul>
      <% @dashboard.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dashboards/edit.html.erb
<h1>Editing dashboard</h1>

<%= render 'form' %>

<%= link_to 'Show', @dashboard %> |
<%= link_to 'Back', dashboards_path %>

app/views/dashboards/index.html.erb
<div id="header">
<h1>Indoor Heating</h1>
</div>

<div id="chart_container">
  <div id="y_axis"></div>
  <div id="chart"></div>
  <div id="legend"></div>
</div>

app/views/dashboards/new.html.erb
<h1>New dashboard</h1>

<%= render 'form' %>

<%= link_to 'Back', dashboards_path %>

app/views/dashboards/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_dashboard_path(@dashboard) %> |
<%= link_to 'Back', dashboards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Hocpoc" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">HOC</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Home", "/"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Graphs</li>
              <li><%= link_to "Heating", "/path1"  %></li>
              <li><%= link_to "Electricity", "/path2"  %></li>
              <li><%= link_to "Water", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>